-- 1 HOUR AGO, PRODUCT_ID 1, 3 ITEMS
INSERT INTO ORDERSAPP_ORDER
(ID, CREATED, UPDATED, STATUS, USER_ID, IS_ACTIVE)
VALUES(10, DATETIME('NOW', '-1 HOUR'), DATETIME('NOW'), 'FM', 1, 1);
INSERT INTO ORDERSAPP_ORDERITEM
(ID, QUANTITY, ORDER_ID, PRODUCT_ID)
VALUES(10, 3, 10, 1);
INSERT INTO ORDERSAPP_ORDERITEM
(ID, QUANTITY, ORDER_ID, PRODUCT_ID)
VALUES(11, 3, 10, 2);
-- 2 HOUR AGO, PRODUCT_ID 2, 4 ITEMS
INSERT INTO ORDERSAPP_ORDER
(ID, CREATED, UPDATED, STATUS, USER_ID, IS_ACTIVE)
VALUES(11, DATETIME('NOW', '-2 HOUR'), DATETIME('NOW'), 'FM', 1, 1);
INSERT INTO ORDERSAPP_ORDERITEM
(ID, QUANTITY, ORDER_ID, PRODUCT_ID)
VALUES(12, 4, 11, 2);
INSERT INTO ORDERSAPP_ORDERITEM
(ID, QUANTITY, ORDER_ID, PRODUCT_ID)
VALUES(13, 4, 11, 3);
-- 3 HOUR AGO, PRODUCT_ID 3, 5 ITEMS
INSERT INTO ORDERSAPP_ORDER
(ID, CREATED, UPDATED, STATUS, USER_ID, IS_ACTIVE)
VALUES(12, DATETIME('NOW', '-3 HOUR'), DATETIME('NOW'), 'FM', 1, 1);
INSERT INTO ORDERSAPP_ORDERITEM
(ID, QUANTITY, ORDER_ID, PRODUCT_ID)
VALUES(14, 5, 12, 3);
INSERT INTO ORDERSAPP_ORDERITEM
(ID, QUANTITY, ORDER_ID, PRODUCT_ID)
VALUES(15, 5, 12, 4);

-- 13 HOUR AGO, PRODUCT_ID 4, 3 ITEMS
INSERT INTO ORDERSAPP_ORDER
(ID, CREATED, UPDATED, STATUS, USER_ID, IS_ACTIVE)
VALUES(20, DATETIME('NOW', '-13 HOUR'), DATETIME('NOW'), 'FM', 1, 1);
INSERT INTO ORDERSAPP_ORDERITEM
(ID, QUANTITY, ORDER_ID, PRODUCT_ID)
VALUES(20, 1, 20, 4);
INSERT INTO ORDERSAPP_ORDERITEM
(ID, QUANTITY, ORDER_ID, PRODUCT_ID)
VALUES(21, 1, 20, 5);
-- 14 HOUR AGO, PRODUCT_ID 5, 3 ITEMS
INSERT INTO ORDERSAPP_ORDER
(ID, CREATED, UPDATED, STATUS, USER_ID, IS_ACTIVE)
VALUES(21, DATETIME('NOW', '-14 HOUR'), DATETIME('NOW'), 'FM', 1, 1);
INSERT INTO ORDERSAPP_ORDERITEM
(ID, QUANTITY, ORDER_ID, PRODUCT_ID)
VALUES(22, 2, 21, 5);
INSERT INTO ORDERSAPP_ORDERITEM
(ID, QUANTITY, ORDER_ID, PRODUCT_ID)
VALUES(23, 2, 21, 6);
-- 15 HOUR AGO, PRODUCT_ID 6, 3 ITEMS
INSERT INTO ORDERSAPP_ORDER
(ID, CREATED, UPDATED, STATUS, USER_ID, IS_ACTIVE)
VALUES(22, DATETIME('NOW', '-15 HOUR'), DATETIME('NOW'), 'FM', 1, 1);
INSERT INTO ORDERSAPP_ORDERITEM
(ID, QUANTITY, ORDER_ID, PRODUCT_ID)
VALUES(24, 3, 22, 6);
INSERT INTO ORDERSAPP_ORDERITEM
(ID, QUANTITY, ORDER_ID, PRODUCT_ID)
VALUES(25, 3, 22, 7);

-- 25 HOUR AGO, PRODUCT_ID 1, 3 ITEMS
INSERT INTO ORDERSAPP_ORDER
(ID, CREATED, UPDATED, STATUS, USER_ID, IS_ACTIVE)
VALUES(30, DATETIME('NOW', '-25 HOUR'), DATETIME('NOW'), 'FM', 1, 1);
INSERT INTO ORDERSAPP_ORDERITEM
(ID, QUANTITY, ORDER_ID, PRODUCT_ID)
VALUES(30, 2, 30, 1);
INSERT INTO ORDERSAPP_ORDERITEM
(ID, QUANTITY, ORDER_ID, PRODUCT_ID)
VALUES(31, 2, 30, 2);
-- 26 HOUR AGO, PRODUCT_ID 2, 3 ITEMS
INSERT INTO ORDERSAPP_ORDER
(ID, CREATED, UPDATED, STATUS, USER_ID, IS_ACTIVE)
VALUES(31, DATETIME('NOW', '-26 HOUR'), DATETIME('NOW'), 'FM', 1, 1);
INSERT INTO ORDERSAPP_ORDERITEM
(ID, QUANTITY, ORDER_ID, PRODUCT_ID)
VALUES(32, 3, 31, 2);
INSERT INTO ORDERSAPP_ORDERITEM
(ID, QUANTITY, ORDER_ID, PRODUCT_ID)
VALUES(33, 3, 31, 3);
-- 27 HOUR AGO, PRODUCT_ID 3, 3 ITEMS
INSERT INTO ORDERSAPP_ORDER
(ID, CREATED, UPDATED, STATUS, USER_ID, IS_ACTIVE)
VALUES(32, DATETIME('NOW', '-27 HOUR'), DATETIME('NOW'), 'FM', 1, 1);
INSERT INTO ORDERSAPP_ORDERITEM
(ID, QUANTITY, ORDER_ID, PRODUCT_ID)
VALUES(34, 4, 32, 3);
INSERT INTO ORDERSAPP_ORDERITEM
(ID, QUANTITY, ORDER_ID, PRODUCT_ID)
VALUES(35, 4, 32, 4);