# Generated by Django 2.2.17 on 2021-03-25 00:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_auto_20210319_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 0, 2, 32, 48189, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
